#!/bin/bash
#usage : energy.sh *.log

rm last.txt
step=$(grep "out of" $1|awk '{print $16}'|tail -n 1)
grep "ONIOM: extrapolated energy =" $1 > energy.txt
grep "out of" $1 > number.txt
paste number.txt energy.txt > total.txt

for (( i=1;i<=${step};i=i+1))
do
    grep -w "$i out of   " total.txt|tail -n 1 >> last.txt
done

awk '{print $21}' last.txt
rm energy.txt number.txt total.txt
