#!/bin/bash

#usage : energy.sh *.log

OUTPUT=${1%.*}
step=$(grep "out of a maximum of" $1|awk '{print $16}'|tail -n 1)

if [[ $(grep "ONIOM: extrapolated energy" $1) != "" ]]; then
    echo "This is a ONIOM job >>>"   
    grep "ONIOM: extrapolated energy =" $1 > energy.tmp
else
    echo "This is a NON-ONIOM job >>>"
    grep "SCF Done:" $1 > energy.tmp
fi

grep "out of a maximum of" $1 > number.tmp
paste number.tmp energy.tmp > total.tmp

for (( i=1;i<=${step};i=i+1))
do
    grep -w "$i out of   " total.tmp | tail -n 1 | awk '{print $3","$9","$13","$16","$21}' >> last.tmp
done

sed -i '1s/^/OptCycle,MaxCycle,ScanStep,TotalStep,Energy(Hartree)\n/' last.tmp

cat last.tmp | perl -pe 's/((?<=,)|(?<=^)),/ ,/g;' | column -t -s,

printf "Note: The last step may not have converged if the job is still running.\n"

rm *.tmp
