#!/bin/sh

# Use Submit -h | --help to show usage.
# Use this script at your own discretion.
# This script automatically calibrates Link0 parms for .gjf files and then inject them through sbatch.

# !!!VERY IMPORTANT!!!
# Multi-gjf simutaneous submit supported! (pass multiple filenames will do.)
# if no %nprocs / %mem / %lindaworkers is assigned, original gjf parms will be respected.
# IF ANY parameter is assigned a value (i.e. "-m 5"), it will be effective on the latter gjfs UNTIL it is re-assigned (i.e. "-m 4")
# This script has gensub_g09/g16 script embedded. No template needed.

# Example: Submit-SLM -p 12 -m 5 -q fat -g g16 -l 4 task1.gjf task2.gjf ...

# Created by Yuanqi Wang @CCMBI, Dec, 2018. Modification Allowed. Absolutely NO WARRANTY!

# Revision: 1.1

###########################################################

# this script combines multiple commands:
# 1. dos2unix <yourgjf>
# 2. Adjust link0 resources parameters (nprocs / mem)
# 3. gensub_gauss <yourgjf> (built in)
# 4. Calibrate sub file
# 5. sbatch <your_sub_bash_script>

###########################################################

#>>>>>>>>>>>>>>>>>>>>  LOOK HERE  <<<<<<<<<<<<<<<<<<<<<<<<<
# This is the section you should tweak before use:
g09C01_root=/lustre/home/acct-clswxl/software/g09.C.01        # root dir of g09 C01 installation.
g09C01_profile=$g09C01_root/g09/bsd/g09.profile               # profiles to be sources for g09

g09D01_root=/lustre/home/acct-clswxl/software/g09.D.01        # root dir of g09 D01 installation.
g09D01_profile=$g09D01_root/g09/bsd/g09.profile               # profiles to be sources for g09

g09E01_root=/lustre/home/acct-clswxl/software/g09.E.01        # root dir of g09 E01 installation.
g09E01_profile=$g09E01_root/g09/bsd/g09.profile               # profiles to be sources for g09

g16A03_root=/lustre/home/acct-clswxl/software/g16.A.03        # root dir of g16 A03 installation.
g16A03_profile=$g16A03_root/g16/bsd/g16.profile               # profiles to be sources for g16

default_queue=cpu                                             # default job queue.
max_nprocs_per_node=16                                        # Maximum nprocs number per node.
#>>>>>>>>>>>>>>>>>>>>  LOOK HERE  <<<<<<<<<<<<<<<<<<<<<<<<<

###########################################################

# Define colors
NC='\033[0m'

Red='\033[0;31m'
Green='\033[0;32m'
Blue='\033[0;34m'
Purple='\033[0;35m'
Yellow='\033[1;33m'

Blink='\033[5m'

###########################################################

# Define Functions:

# help / usage function:
usage()
{
    printf "${Red}SYNOPSIS${NC}\n\n"
    printf "  ${Yellow}Submit${NC} (SJTU HPC Sbatch Edition)\n"
    printf "    (no args) ${Blue}...${NC} respect original gjf parameters and submit.\n"
    printf "    [-h | --help] show this help.\n"
    printf "    [-l | --linda] ${Green}<Lindaworkers No.> ${Blue}...${NC} Assign ${Green}<Lindaworkers No.>${NC} to ${Red}%%lindaworkers${NC}.\n"
    printf "    [-m | --mem] ${Green}<Mem Size>${NC} ${Blue}...${NC} Assign ${Green}<Mem Size>${NC} to ${Red}%%mem${NC}.\n"
    printf "    [-p | --nprocs] ${Green}<Procs No.>${NC} ${Blue}...${NC} Assign ${Green}<Procs No.>${NC} to ${Red}%%nprocs${NC}.\n"
    printf "                   ${Red}%%nprocshared${NC} in gjf is equal to ${Purple}Proc(s) per Node (ppn)${NC}. \n"
    printf "    [-q | --queue] ${Green}<Queue Name>${NC} ${Blue}...${NC} Change designated queue to ${Green}<Queue Name>${NC}.\n"
    printf "    [-g | --gauss] ${Green}<Gaussian Version>${NC} ${Blue}...${NC} Designate specific Gaussian Version.\n"
    printf "                   Available versions: ${Blue}g09C01 / g09D01 / g09E01 / g16${NC} .\n"
    printf "    [-t | --test] make calibrations, but ${Red}DOES NOT${NC} submit.\n\n"
    printf "${Red}DESCRIPTION${NC}\n\n"
    printf "  ${Yellow}\'Submit\'${NC} is used to calibrate Gaussian input files and inject through sbatch.\n"
    printf "  Arguments above can be mixed. each argument is effective ${Purple}until it is re-defined${NC}.\n"
    printf "  Wildcard supported. Try it out!\n"
    printf "  Created with ${Red}LOVE${NC} by ${Blue}Yuanqi Wang${NC} ${Purple}@CCMBI${NC}(Dec, 2018). ${Yellow}ABSOLUTELY NO WARRANTY!${NC}\n\n"
}

# built-in gensub_g09/g16 function, adapted from original gensub_g09/g16 script:
   # example of $1 is: /path/to/gjf/example.gjf

gen_gauss_embedded()
{
    # parse directory / filename
    gjf_dir=`dirname $1`  # get input file directory.           i.e. /path/to/gjf
    gjf_file=`basename $1`       # filename without path.       i.e. example.gjf
    gjf_name=${gjf_file%.*}      # filename without extension.  i.e. example
    
    cd ${gjf_dir} # change directory
    
    # parse %nprocs and %lindaworkers parameters
    # NOTE! because gjf was turned lowercase before this function, we will match only lowercase!
    gjf_nprocs=$(grep -o -P -m 1 '(?<=%nprocs=)\d*' $gjf_file)
    gjf_linda=$(grep -o -P -m 1 '(?<=%lindaworkers=)\d*' $gjf_file)
    
    # print possible warning:
    if [ "${gjf_nprocs}" -lt "${max_nprocs_per_node}" ] # NOT exclusive
        then
            printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} has ${Green}%%nprocs${NC}=${Yellow}$gjf_nprocs${NC} less than ${Red}${max_nprocs_per_node}${NC}.\n"
            printf "${Yellow}${Blink}Warning${NC}: You are NOT using nodes exclusively. Recalibration recommended.\n"
    fi
    
    if [ "${gjf_linda}" -gt 1 ]                         # Parallel multiple nodes
        then
            printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} has ${Green}%%lindaworkers${NC} more than ${Red}1${NC}.\n"
            printf "${Yellow}${Blink}Warning${NC}: You may want to check maximum ${Green}%%lindaworkers${NC} of each queue.\n"
    fi
    
    # prepare sub file variables >>>
    
    # 1. queue line:
    if [ -n "${queue}" ]    # if $queue is defined:
        then
            slm_queue="${queue}"
        else
            slm_queue="${default_queue}"  # change this in the beginning of the script
    fi
    
    # 2. cpus line:
    slm_cpus=`echo ${gjf_linda}*${gjf_nprocs} | bc`
    
    # 3. prepare Gaussian ENV export lines:
    # !!!Tweak this part if new versions are added.!!!
    case $gauss_ver in
        g09C01 )
            export_line="export g09root=$g09C01_root"
            source_line="source $g09C01_profile"
            EXE="g09"
            ;;
        g09D01 )
            export_line="export g09root=$g09D01_root"
            source_line="source $g09D01_profile"
            EXE="g09"
            ;;
        g09E01 )
            export_line="export g09root=$g09E01_root"
            source_line="source $g09E01_profile"
            EXE="g09"
            ;;
        g16A03 )
            export_line="export g16root=$g16A03_root"
            source_line="source $g16A03_profile"
            EXE="g16"
            ;;
        * )
            printf "${Red}${Blink}Error:${NC} Gaussian Version NOT defined.\n"
            printf "${Green}Info${NC}: Type ${Blue}\'Submit [-h | --help]\'${NC} for help.\n"
            exit 1
    esac
    # export Gaussian ENV variables completed <<<<  
    
    # writing SLM submit script >>>
    submit_script=sub_gauss_${gjf_name}.sh
    rm sub_gauss_${gjf_name}.sh 2> /dev/null
    
    touch sub_gauss_${gjf_name}.sh
    
    echo -e "#!/bin/bash\n"                                    >> sub_gauss_${gjf_name}.sh
    
    echo -e "#SBATCH --job-name=${gjf_name}"                   >> sub_gauss_${gjf_name}.sh
    echo -e "#SBATCH --output=${gjf_name}_%j.info"             >> sub_gauss_${gjf_name}.sh
    echo -e "#SBATCH --error=${gjf_name}_%j.info"              >> sub_gauss_${gjf_name}.sh
    echo -e "#SBATCH -p ${slm_queue}"                          >> sub_gauss_${gjf_name}.sh
    echo -e "#SBATCH -n ${slm_cpus}"                           >> sub_gauss_${gjf_name}.sh
    echo -e "#SBATCH --ntasks-per-node=${gjf_nprocs}"          >> sub_gauss_${gjf_name}.sh
    echo -e "#SBATCH --time=168:00:00"                         >> sub_gauss_${gjf_name}.sh
    echo -e "###SBATCH --exclusive\n"                          >> sub_gauss_${gjf_name}.sh # default not exclusive

    echo -e "###SLURM Parameters are all listed above###\n"    >> sub_gauss_${gjf_name}.sh
    
    echo -e "###Removing output / error file defined above:###"  >> sub_gauss_${gjf_name}.sh
    echo -e "rm ${gjf_name}_*.info\n"                          >> sub_gauss_${gjf_name}.sh

    echo -e "###Exporting/Sourcing Gaussian ENVs:###"          >> sub_gauss_${gjf_name}.sh
    echo -e "${export_line}"                                   >> sub_gauss_${gjf_name}.sh
    echo -e "${source_line}\n"                                 >> sub_gauss_${gjf_name}.sh
    
    echo -e "###Executing Gaussian:###"                        >> sub_gauss_${gjf_name}.sh
    echo -e "${EXE} ${gjf_file}\n"                             >> sub_gauss_${gjf_name}.sh
    # writing SLM submit script complete >>>
}



# >>> Main execution starts here >>>
if_submit=true  # flag: whether to submit through sbatch.
input_file=false    # flag: whether at least 1 gjf is imported.
gauss_ver=g09D01    # Gaussian Version set default to g09D01

if [ "$1" != "" ]   # if arguments / files are imported.
    then
        while [ "$1" != "" ]    # read in parameters and files one by one.
            do
                case $1 in
                    -h | --help )   # help
                        usage
                        exit 0
                        ;;
                    -g | --gauss )  # Gaussian Version
                        shift
                        gauss_ver=$1
                        ;;
                    -p | --nprocs ) # CPU core numbers.
                        shift
                        re='^[0-9]+$' # Must be integer.
                        if ! [[ $1 =~ $re ]]    # If not integer.
                            then
                                printf "${Red}${Blink}Error:${NC} ${Green}%%nprocs${NC} needs to be an ${Red}integer${NC}!\n"
                                exit 1
                            else
                                nprocs=$1   # assign $1 to variable nprocs
                        fi
                        ;;
                    -m | --mem )    # memory size (in GB)
                        shift
                        re='^[0-9]+$'   # Must be integer.
                        if ! [[ $1 =~ $re ]]    # If not integer.
                            then
                                printf "${Red}${Blink}Error:${NC} ${Green}%%mem${NC} needs to be an ${Red}integer${NC}!\n"
                                exit 1
                            else
                                mem=$1   # assign $1 to variable mem
                        fi
                        ;;
                    -l | --linda )  # lindaworkers numbers
                        shift
                        re='^[0-9]+$'   # Must be integer.
                        if ! [[ $1 =~ $re ]]    # If not integer.
                            then
                                print "${Red}${Blink}Error:${NC} ${Green}%%lindaworkers${NC} needs to be an ${Red}integer${NC}!\n"
                                exit 1
                            else
                                linda=$1  # assign $1 to variable linda
                        fi
                        ;;
                    -q | --queue )  # queue name.
                        shift
                        queue=$1    # assign queue name to variable queue.
                        ;;
                    -t | --test )   # enter test mode: do not submit generated sub files.
                        if_submit=false # change flag status to false.
                        ;;
                    * )
                        if [ -f $1 ]    # if the input file exists.
                            then
                                input_file=true # mark at least 1 gjf input successful.
                                dos2unix $1 2> /dev/null # essential to get rid of "^M"s (DOS special)
                                
                                # turn all "%" lines to lowercase (global for regex):
                                sed -i "s/%.*=/\L\0/g" $1
                                
                                # overwrite parameters in gjf >>>
                                # 1. get original parms. (they may not exist!)
                                gjf_nprocs=$(grep -o -P -m 1 '(?<=%nprocs=)\d*' $1)
                                gjf_linda=$(grep -o -P -m 1 '(?<=%lindaworkers=)\d*' $1)
                                gjf_mem=$(grep -o -P -m 1 '(?<=%mem=)\d*' $1)
                                
                                # 2. overwrite %nprocs
                                if [ -n "${nprocs}" ] # if any -nprocs was set previous to this gjf:
                                    then
                                        if [ "$gjf_nprocs" != "" ]
                                            then
                                                sed -i "s/%nprocs=.*/%nprocs=${nprocs}/g"  $1    # replace original nprocs value.
                                            else
                                                sed -i "1 i\%nprocs=${nprocs}" $1
                                        fi
                                    else
                                        if [ "$gjf_nprocs" == "" ]
                                            then
                                                printf "${Red}${Blink}Error${NC}: ${Green}$1${NC} requires a ${Green}%%nprocs${NC} parameter.\n"
                                                printf "${Red}${Blink}Error${NC}: ${Green}$1${NC} was ignored.\n"
                                                shift
                                                continue
                                        fi
                                fi
                                
                                # 3. overwrite %mem
                                if [ -n "${mem}" ] # if any -mem was set previous to this gjf:
                                    then
                                        if [ "$gjf_mem" != "" ]
                                            then
                                                sed -i "s/%mem=.*/%mem=${mem}GB/g"  $1    # replace original mem value.
                                            else
                                                sed -i "1 i\%mem=${mem}GB" $1
                                        fi
                                    else
                                        if [ "$gjf_mem" == "" ]
                                            then
                                                printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} does NOT have ${Green}%%mem${NC} defined.\n"
                                                printf "${Yellow}${Blink}Warning${NC}: ${Green}%%mem${NC} of ${Green}$1${NC} will be automatically defined by Gaussian.\n"
                                        fi
                                fi
                                
                                # 4. overwrite %lindaworkers
                                if [ -n "${linda}" ] # if any -lindaworkers was set previous to this gjf:
                                    then
                                        if [ "$gjf_linda" != "" ]
                                            then
                                                sed -i "s/%lindaworkers=.*/%lindaworkers=${linda}/g"  $1    # replace original lindaworkers value.
                                            else
                                                sed -i "1 i\%lindaworkers=${linda}" $1
                                        fi
                                    else
                                        if [ "$gjf_linda" == "" ]
                                            then
                                                printf "${Red}${Blink}Error${NC}: ${Green}$1${NC} requires a ${Green}%%lindaworkers${NC} parameter\n"
                                                printf "${Red}${Blink}Error${NC}: ${Green}$1${NC} was ignored.\n"
                                                shift
                                                continue
                                        fi
                                fi
                                # parm overwrite completed <<<<
                                
                                # generate sub_gauss_xxx.sh files after .gjf is ready
                                gen_gauss_embedded $1         # generate .sh submission file
                                submit_sh="sub_gauss_${1%.*}.sh" # locate sub_gauss_xxx.sh filename
                                
                                # submit
                                if [ "$if_submit" = true ]
                                    then
                                        id=$(sbatch ${submit_sh} | awk '{print $4}') # submit job to sbatch, return id.
                                        rm "sub_gauss_${1%.*}.sh" # trash submission file
                                        if [ -n "${id}" ] # if id is not empty
                                            then
                                                printf "${Green}Info${NC}: ${Green}$1${NC} submitted to queue ${Purple}${slm_queue}${NC} as job ${Red}${id}${NC}, ${Purple}${gjf_linda}${NC} * ${Purple}${gjf_nprocs}${NC} cores used.\n"
                                            else
                                                printf "${Red}${Blink}Error${NC}: ${Green}$1${NC} submission ${Red}ERROR${NC}!.\n"
                                        fi
                                    else
                                        printf "${Yellow}${Blink}Warning${NC}: ${Green}$1${NC} NOT submitted.\n"
                                fi
                            else
                                printf "${Red}${Blink}Error:${NC} Unknown argument or file not exist.\n"
                                printf "${Green}Info${NC}: Type ${Blue}\'Submit [-h | --help]\'${NC} for help.\n"
                                exit 1
                        fi
                esac
                shift
            done

            if [ "$input_file" = false ]
                then
                    printf "${Red}${Blink}Error:${NC} No input gjf files.\n${Green}Info${NC}: Type ${Blue}\'Submit [-h | --help]\'${NC} for help.\n"
                    exit 1
            fi

        exit 0
    else
        usage
        exit 1
fi
exit 0
# <<< Main execution completed <<<
